site_name: '${{ values.name }}'
site_description: 'Main documentation for ${{ values.name }}'
repo_url: https://github.com/${{ values.destination.owner }}/${{ values.destination.repo }}
edit_uri: edit/main/docs

plugins:
  - techdocs-core

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.json`
nav:
  - Overview:
      - Getting started: 'docs/index.md'